import {Region} from "../../../../core/models/region.model";
import {Prefecture} from "../../../../core/models/prefecture.model";
import {Commune} from "../../../../core/models/commune.model";
import {DomaineActivite} from "../../../../core/models/domaine-activite.model";
import {TypeSociete} from "../../../../core/models/type-societe.model";
import {User} from "../../../../core/models/auth.models";

export interface GridModel {
  address?:  any;
  aguipe_document?:  any;
  approx_turnover?:  any;
  attend_workshop?:  any;
  categories?:  DomaineActivite[];
  commune?:  Commune;
  conflict_of_interrest?:  any;
  created_at?:  any;
  credit_checks?:  any;
  criminal_offence?:  any;
  debarred?:  any;
  declare_true?:  any;
  description?:  any;
  disable_number?:  any;
  email?:  any;
  employee_disabled?:  any;
  etat_financier_document?:  any;
  expired_date?:  any;
  expiry_reminder?:  any;
  facebook_url?:  any;
  good_service_provided?:  any;
  id?:  any;
  industry_qualifications?:  any;
  instagram_url?:  any;
  is_active?:  any;
  linkedin_url?:  any;
  local_content?:  any;
  local_content_file?:  any;
  logo?:  any;
  logo_height?:  any;
  logo_ppoi?:  any;
  logo_width?:  any;
  name?:  any;
  nif_document?:  any;
  ninea?:  any;
  number_of_branches?:  any;
  number_of_employees?:  any;
  ownership_under_35?:  any;
  ownership_women?:  any;
  phone_number?:  any;
  prefecture?:  Prefecture;
  quitus_fiscal_document?:  any;
  quitus_social_document?:  any;
  rccm?:  any;
  rccm_document?:  any;
  region?:  Region;
  registered_by?:  any;
  slug?:  any;
  status?:  any;
  statut_document?:  any;
  tier?:  any;
  tiktok_url?:  any;
  type?:  TypeSociete;
  udpated_at?:  any;
  understand_risk?:  any;
  website?:  any;
  woman_ownership_percentage?:  any;
  year_of_registration?:  any;
  social_capital?:  any;
  chiffre_affaire?:  any;

}
